# What is an Orthogonal Matrix?

[Resource](https://www.thesecuritybuddy.com/linear-algebra/how-to-create-an-orthogonal-matrix-using-python-numpy/)

A **square matrix** is said to be an orthogonal matrix if the following condition holds true:

AA^T = A^T A = I

Now, we know that, if A and B are two matrices such that the following condition holds true:

AB = I
B = A^-1

then, B is said to be the inverse of matrix A.

So, we can say that for an orthogonal matrix A:

AA^T = A^TA = I
A^T = A^-1

So, in other words, a square matrix A is an orthogonal matrix, if the transpose of the matrix A is equal to the inverse of the matrix A.

For example, let's say A is the following matrix:

In [4]:
import numpy as np

# 2D array
A = np.array([[1, 0],
              [0, -1]])
A

array([[ 1,  0],
       [ 0, -1]])

The transpose of A is:

In [24]:
At = np.transpose(A)

I = np.linalg.inv(A)

equal_check1 = A == At
equal_check2 = At == I

print(At,"\n")
print(equal_check1)
print(equal_check2)

[[ 1  0]
 [ 0 -1]] 

[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]


In other words, the transpose of matrix `A` is equal to the inverse of matrix `A`.

And,

In [10]:
AAt = A * At
print(f"`AAt`\n{AAt}\n")

I = AAt
print(f"`I`\n{I}\n")

`AAt`
[[1 0]
 [0 1]]

`I`
[[1 0]
 [0 1]]



Therefore,

In [16]:
print(f"`AAt`\n{AAt}\n=")

print(f"At * A\n{At * A}\n=")

print(f"`I`\n{I}")

`AAt`
[[1 0]
 [0 1]]
=
At * A
[[1 0]
 [0 1]]
=
`I`
[[1 0]
 [0 1]]


Hence, AQ is an orthogonal matrix.