# Understanding the Components of SVD

[Resource](https://codesignal.com/learn/courses/eigenvalues-eigenvectors-and-diagonalization-with-numpy/lessons/singular-value-decomposition-svd-with-numpy)

Singular Value Decomposition decomposes a given matrix A into three simpler matrices: U, S, and V^T. When you decompose matrix A, the singular values are the diagonal entries of the <mi mathvariant="normal">&#x3A3;</mi> matrix. THey measure how much each corresponding pair of singular vectors (columns of U and V) contributes to reconstructing the original matrix.

- **U Matrix:** An orthogonal matrix that represents the left singular vectors
- **Singular Values (S)** These are diagonal elements and represent the magnitudes of the axes.
- **V Transpose Matrix (V^T):** Another orthogonal matrix representing the right singular vectors.

Imagine each matrix as playing a role in a transformation. By breaking down A into three components, we can analyze and manipulate the matrix in more intuitive ways.

## Definitions

**Orthogonal Matrix**

Refer to `Orthogonal Matrices.ipynb`.

**Left Singular Vectors**

The columns of matrix U. They represent the directions of maximum variance in the output space when A acts as a linear transformation.

**Right Singular Vectors**

The columns of matrix V. These are also orthogonal vectors that span the row space of A. They represent the maximum variance in the input space.

# Hands-On Example

Let's walk through an example to see how SVD is performed using NumPy. We'll use the following matrix and decompose it using NumPy's SVD function:

In [23]:
import numpy as np

matrix = np.array([[1, 2, 3],
                  [4, 5, 6]])

U, S, Vt = np.linalg.svd(matrix)

print("Matrix:\n", matrix)
print("U Matrix:\n", U)
print("Singular Values:", S)
print("V Transpose Matrix:\n", Vt)

Matrix:
 [[1 2 3]
 [4 5 6]]
U Matrix:
 [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
Singular Values: [9.508032   0.77286964]
V Transpose Matrix:
 [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


# Interpreting SVD Results

Now that we've obtained the results, let's interpret them:

- The **U Matrix** provides the directions of the left singular vectors, showing how the rows are transformed.
- The **Singular Values** reflect the magnitude by which the data is stretched in each direction.
- The **V Transpose Matrix** specifies the directions of the right singular vectors, indicating how the columns are transformed.

These components help us understand and manipulate data effectively, making SVD a valuable technique in data processing and improvement.

# My Personal Example

You can also use the `scipy` module to create orthogonal matrices:

In [16]:
from scipy.stats import ortho_group

A = ortho_group.rvs(dim=2)
print(A)

A_inverse = np.linalg.inv(A)
A_transpose = np.transpose(A)

equal_check = np.allclose(A_inverse, A_transpose)
equal_check

[[-0.4036125   0.91493002]
 [-0.91493002 -0.4036125 ]]


True

In [17]:
print(f"Original A\n{A}\n")
print(f"Inverse A\n{A_inverse}\n")
print(f"Transposed A\n{A_transpose}")

Original A
[[-0.4036125   0.91493002]
 [-0.91493002 -0.4036125 ]]

Inverse A
[[-0.4036125  -0.91493002]
 [ 0.91493002 -0.4036125 ]]

Transposed A
[[-0.4036125  -0.91493002]
 [ 0.91493002 -0.4036125 ]]
